apiVersion: v1
kind: Namespace
metadata:
  name: jvmoperator
---
apiVersion: v1
kind: Pod
metadata:
  namespace: jvmoperator
  name: custom-operator
spec:
  serviceAccountName: operator-service
  containers:
    - name: custom-operator
      image: jvm-operator:2.0
      imagePullPolicy: Never
      volumeMounts:
        - name: share
          mountPath: /graalvm/config
  volumes:
    - name: share
      hostPath:
        path: /graalvm/config
